AWSTemplateFormatVersion: 2010-09-09
Description: SCP Backup SSH Sec Group
Mappings: {}

Parameters:
  VPCStack:
    Type: String
    Default: Buildstacks-VPC
  SecurityGroupName:
    Type: String
    Default: SCPBackup
  NetworkCIDR:
    Type: String
    Default: 0.0.0.0/0

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Ref SecurityGroupName
      GroupDescription: "Enable SSH access"
      VpcId: 
        Fn::ImportValue:
          !Sub "${VPCStack}-VPCid"
      SecurityGroupEgress:
        -
          IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref NetworkCIDR

Outputs:
  SecurityGroup:
    Description: Backup SCP Sec Group
    Export:
      Name: !Sub "${AWS::StackName}-SecGroup-${SecurityGroupName}"
    Value: !Ref SecurityGroup
